/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;
import AccesoADatos.MateriaData;
import AccesoADatos.AlumnoData;
import AccesoADatos.InscripcionData;
import Entidades.Alumno;
import Entidades.Inscripcion;
import Entidades.Materia;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Arian
 */
public class ViewFormInscripcion extends javax.swing.JInternalFrame {
    
    private DefaultTableModel modelo;
    private ArrayList<Materia> listaMateria;
    private ArrayList<Alumno> listaAlumno;
    private InscripcionData inscripcionData;
    private MateriaData materiaData;
    private AlumnoData alumnoData;
    
    
    
    
    
    public ViewFormInscripcion() {
        initComponents();
        modelo = new DefaultTableModel();
        alumnoData= new AlumnoData();
        materiaData= new MateriaData();
        listaAlumno= (ArrayList<Alumno>) alumnoData.listarAlumnos();
        listaMateria= (ArrayList<Materia>) materiaData.listarMaterias();
        inscripcionData = new InscripcionData();
        cargarCombo();
        armarTabla();
        botonInscribir.setEnabled(false);
        botonAnularInscripcion.setEnabled(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        rbIncriptas = new javax.swing.JRadioButton();
        rbNoInscriptas = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        botonInscribir = new javax.swing.JButton();
        botonAnularInscripcion = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Formulario de inscripcion");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Seleccione un alumno");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Listado de materias");

        rbIncriptas.setText("Materias inscriptas");
        rbIncriptas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbIncriptasActionPerformed(evt);
            }
        });

        rbNoInscriptas.setText("Materias no Inscriptas");
        rbNoInscriptas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNoInscriptasActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        botonInscribir.setText("Inscribir");
        botonInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInscribirActionPerformed(evt);
            }
        });

        botonAnularInscripcion.setText("Anular Inscripcion");
        botonAnularInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAnularInscripcionActionPerformed(evt);
            }
        });

        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbIncriptas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbNoInscriptas)
                        .addGap(57, 57, 57))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(9, 9, 9)
                                    .addComponent(botonInscribir, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(botonAnularInscripcion)
                                    .addGap(78, 78, 78)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(21, 21, 21)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(7, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbIncriptas)
                    .addComponent(rbNoInscriptas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonInscribir)
                    .addComponent(botonAnularInscripcion)
                    .addComponent(jButton3))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbIncriptasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbIncriptasActionPerformed
            borrarFilas();
            rbNoInscriptas.setSelected(false);
            cargarMateriasInscriptas();
            botonAnularInscripcion.setEnabled(true);
            botonInscribir.setEnabled(false);
    }//GEN-LAST:event_rbIncriptasActionPerformed

    private void rbNoInscriptasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNoInscriptasActionPerformed
        borrarFilas();
        rbIncriptas.setSelected(false);
        cargarMateriasNoInscriptas();
        if (modelo.getRowCount()==0) {
            botonAnularInscripcion.setEnabled(true);
        }
        botonInscribir.setEnabled(true);
        botonAnularInscripcion.setEnabled(false);
    }//GEN-LAST:event_rbNoInscriptasActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void botonInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInscribirActionPerformed
        
        int rowSelected=jTable1.getSelectedRow();
        if (rowSelected!=-1) {
            
            try{
                Alumno a =(Alumno) jComboBox1.getSelectedItem();
                
               int idM = (Integer) modelo.getValueAt(rowSelected, 0);
               String nM= (String) modelo.getValueAt(rowSelected, 1);
               int anio =(Integer) modelo.getValueAt(rowSelected, 2);
               
               Materia m = new Materia(idM,nM,anio,true);
               
               Inscripcion i = new Inscripcion(a,m,0);
               
               inscripcionData.guardarInscripcion(i);
               
               borrarFilas();
               
               JOptionPane.showMessageDialog(this, "Se Inscribio correctamente");
            
            }catch(Exception e){}
            
        }else{
             JOptionPane.showMessageDialog(this, "Por favor Seleccione una materia de la tabla");
            
        }
        
        
    }//GEN-LAST:event_botonInscribirActionPerformed

    private void botonAnularInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAnularInscripcionActionPerformed
        int rowSelected=jTable1.getSelectedRow();
        
         if (rowSelected!=-1) {
            
            try{
               Alumno al =(Alumno) jComboBox1.getSelectedItem();
               int idMa = (Integer) modelo.getValueAt(rowSelected, 0);
               inscripcionData.borrarInscripcionMateriaAlumno(al.getIdAlumno(), idMa);
               borrarFilas();
               JOptionPane.showMessageDialog(this, "Inscripcion anulada correctamente");
               
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, "Error Inesperado");
            
            
            }
            
        }else{
         
             JOptionPane.showMessageDialog(this, "Por favor Seleccione una materia de la tabla");
         
         }
        
    }//GEN-LAST:event_botonAnularInscripcionActionPerformed

    
    private void armarTabla(){
        ArrayList <Object> filaTabla = new ArrayList<>();
        filaTabla.add("ID");
        filaTabla.add("Nombre");
        filaTabla.add("Año");
        for (Object it: filaTabla) {
            modelo.addColumn(it);
        }
        
        jTable1.setModel(modelo);
    
    
    
    }
    
    
    public void borrarFilas(){
        int index = modelo.getRowCount() -1;
        
        for (int i = index; i >=0; i--) {
            
            modelo.removeRow(i);
        }
        
    
    }
    
    public void cargarMateriasNoInscriptas(){
    
        Alumno alum = (Alumno) jComboBox1.getSelectedItem();
        listaMateria = (ArrayList<Materia>) inscripcionData.obtenerMateriasNOCursadas(alum.getIdAlumno());
        for (Materia m: listaMateria) {
           modelo.addRow(new Object[] {m.getIdMateria(), m.getNombre(), m.getAnio()});
        }
        
    
    }
    
    
    public void cargarMateriasInscriptas(){
        Alumno alum = (Alumno) jComboBox1.getSelectedItem();
        
        listaMateria=(ArrayList<Materia>) inscripcionData.obtenerMateriasCursadas(alum.getIdAlumno());
        for (Materia m: listaMateria) {
            modelo.addRow(new Object [] {m.getIdMateria(), m.getNombre(),m.getAnio()});
        }
    
    
    }
    
    public void cargarCombo(){
        ArrayList <Alumno> listaAlumnos = new ArrayList<>();
        
        listaAlumnos = (ArrayList<Alumno>) alumnoData.listarAlumnos();
        
        
        for(Alumno alu:listaAlumnos){
        
            jComboBox1.addItem(alu);
        
        }
            
    
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAnularInscripcion;
    private javax.swing.JButton botonInscribir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<Alumno> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton rbIncriptas;
    private javax.swing.JRadioButton rbNoInscriptas;
    // End of variables declaration//GEN-END:variables
}
